# Generated by Django 6.0.2 on 2026-02-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_batch_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_user_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], max_length=10)),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
