# Generated by Django 6.0.2 on 2026-02-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_delete_student'),
        ('profiles', '0002_batchadmin_alter_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='batch.batches'),
        ),
    ]
