# Generated by Django 6.0.2 on 2026-02-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
