# Generated by Django 6.0.2 on 2026-03-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_delete_student'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='program_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='institution.program'),
        ),
    ]
