# Generated by Django 6.0.2 on 2026-02-25 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0004_skill_profile_bio_profile_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('status_choice', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=15)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorReq', to='profiles.profile')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
