# Generated by Django 6.0.2 on 2026-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrations',
            name='otp',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
