# Generated by Django 6.0.2 on 2026-02-25 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentorshiprequest'),
        ('profiles', '0004_skill_profile_bio_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorReq', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
