# Generated by Django 6.0.2 on 2026-02-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrations_is_verified_registrations_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
