# Generated by Django 6.0.2 on 2026-02-27 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mentorshiprequest_receiver_and_more'),
        ('profiles', '0004_skill_profile_bio_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='pair_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='mentorshiprequest',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_mentorship_request'),
        ),
    ]
